
name: Test CI (VULNERABLE)

on:
  workflow_run:
    workflows: ['Build CI']
    types: [completed]

jobs:
  demo:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ⚠️ VULNÉRABLE : interpolation directe d'entrées non fiables
      - name: Read PR metadata (VULNERABLE)
        shell: bash
        run: |
          echo "Checking conditions to merge PR with id ${{ github.event.number }}"
          echo "Checking PR title: ${{ github.event.pull_request.title }}"
